package com.hgames.rhogue.generation.map.rgenerator;

import java.util.HashSet;

import com.hgames.rhogue.generation.map.Dungeon;
import com.hgames.rhogue.generation.map.DungeonGenerator;

import squidpony.squidgrid.zone.Zone;
import squidpony.squidmath.Coord;

/**
 * A room generator, i.e. a function that knows out to generate a {@link Zone}
 * that fit within a rectangle.
 * 
 * @author smelC
 */
public interface IRoomGenerator {

	/**
	 * @param dungeon
	 *            The dungeon being built. Usually useless but handy for debugging.
	 * @param translation
	 *            The translation that will be applied to the room when placing it.
	 *            Usually useless but handy for debugging.
	 * @param maxWidth
	 *            The width of the rectangle in which the returned zone must fit.
	 *            Greater than 0.
	 * @param maxHeight
	 *            The height of the rectangle in which the returned zone must fit.
	 *            Greater than 0.
	 * @return A zone such that
	 *         {@code new Rectangle(Coord.get(0, 0), maxWidth, maxHeight).contains(result)}
	 *         holds and such that any member is reachable from all other members.
	 * 
	 *         <p>
	 *         The returned zone iterating order must be stable (don't implement
	 *         {@link Zone#getAll()} with a {@link HashSet} for example).
	 *         </p>
	 * 
	 *         <p>
	 *         Or null if the size constraint cannot be honored.
	 *         </p>
	 */
	public /* @Nullable */ Zone generate(Dungeon dungeon, Coord translation, int maxWidth, int maxHeight);

	/**
	 * @return Whether zones generated by
	 *         {@link #generate(Dungeon, Coord, int, int)} must be kept perfect by
	 *         {@link DungeonGenerator}. A perfect room is a room whose neighbors
	 *         are only walls or outgoing corridors (no chasm, no water).
	 */
	public boolean requiresPerfect();

}
