package com.hgames.rhogue.generation.map.rgenerator;

/**
 * @author smelC
 */
public abstract class SkeletalRoomGenerator implements IRoomGenerator {

	protected boolean requiresPerfect = false;

	/** The maximum number of connections of rooms generated by this generator */
	protected int maxConnections = Integer.MAX_VALUE;

	protected boolean forceDoors = false;

	@Override
	public void setRequiresPerfect(boolean val) {
		this.requiresPerfect = val;
	}

	@Override
	public void setMaxConnections(int val) {
		this.maxConnections = val;
	}

	@Override
	public void setForceDoors(boolean val) {
		this.forceDoors = val;
	}

	@Override
	public boolean requiresPerfect() {
		return requiresPerfect;
	}

	@Override
	public int getMaxConnections() {
		return maxConnections;
	}

	@Override
	public boolean getForceDoors() {
		return forceDoors;
	}
}
